Mitigate InvariantDisks's race with boot-time zpool import -a

diff --git a/etc/launchd/launchd.d/zpool-import-all.sh.in b/etc/launchd/launchd.d/zpool-import-all.sh.in
--- a/etc/launchd/launchd.d/zpool-import-all.sh.in
+++ b/etc/launchd/launchd.d/zpool-import-all.sh.in
@@ -1,7 +1,43 @@
 #!/bin/bash
 
+echo "+zpool-import-all.sh"
+date
 export ZPOOL=@sbindir@/zpool
 export ZPOOL_IMPORT_ALL_COOKIE=/tmp/org.openzfsonosx.did-zpool-import-all
+export INVARIANT_DISKS_IDLE_FILE=/var/run/disk/invariant.idle
+export TIMEOUT_SECONDS=10
+export MAXIMUM_SLEEP_ITERATIONS=$((${TIMEOUT_SECONDS} * 10))
+
+echo "Waiting up to ${TIMEOUT_SECONDS} seconds for the InvariantDisks idle file ${INVARIANT_DISKS_IDLE_FILE} to exist"
+
+i=0
+while [ "${i}" -lt "${MAXIMUM_SLEEP_ITERATIONS}" -a ! -e "${INVARIANT_DISKS_IDLE_FILE}" ]
+do
+	i=$((i+1))
+	sleep .1
+done
+
+if [ -e "${INVARIANT_DISKS_IDLE_FILE}" ]
+then
+	echo "Found ${INVARIANT_DISKS_IDLE_FILE} after ${i} iterations of sleeping 0.1 seconds"
+else
+	echo "File ${INVARIANT_DISKS_IDLE_FILE} not found within ${TIMEOUT_SECONDS} seconds"
+fi
+date
+
+echo "Running zpool import -a"
+date
 
 "${ZPOOL}" import -a
+ret=$?
+
+date
+echo "Finished running zpool import -a : ${ret}"
+
+echo "Touching the file ${ZPOOL_IMPORT_ALL_COOKIE}"
 touch "${ZPOOL_IMPORT_ALL_COOKIE}"
+
+date
+echo "-zpool-import-all.sh"
+
+exit 0
